### ISSUE TITLE
No default projection is set

### ISSUE THREAD

**Issue by mamoll** [ompl/ompl#611]
**[Original report](https://bitbucket.org/ompl/ompl/issue/490) by David Boon (Bitbucket: [boonflies](https://bitbucket.org/boonflies), GitHub: [boonflies](https://github.com/boonflies)).**

----------------------------------------

I am trying to benchmark OMPL planners with the help of RVIZ motion planning plugin. Benchmarking worked fine for RRT related planners and when I tried to benchmark the SBL planner, I receive the following error ,

**[ERROR] [1544418494.591651878, 3813.522000000]: No default projection is set. Perhaps setup() needs to be called
[ERROR] [1544418494.603660381, 3813.522000000]: OMPL encountered an error: No projection evaluator specified
================================================================================REQUIRED process [moveit_run_benchmark-2] has died!**

I am using the following yaml file,
```
#!xml


benchmark_config:
    warehouse:
        host: 127.0.0.1
        port: 33829
        scene_name: obstacle1     # Required
    parameters:
        name: TrialQuery1
        runs: 50
        group: freeFlight       # Required
        timeout: 10.0
        output_directory: /tmp/moveit_benchmarks/
        queries: obstaclequery1
        start_states: obstaclestart1
    planners:
        - plugin: ompl_interface/OMPLPlanner
          planners:
            - RRTConnectkConfigDefault
            - SBLkConfigDefault
```

Should I be adding some additional information for SBL planner?

**Comment by VitaminLL** [comment]
Hi, did u found any solutions?

**Comment by mamoll** [comment]
This usually means that the <robot>_moveit_config/config/ompl_planning.yaml is missing a projection specification for the set of joints being planned for. See https://ros-planning.github.io/moveit_tutorials/doc/ompl_interface/ompl_interface_tutorial.html. For the Panda arm, you'll find examples like these:
```
panda_arm:
  planner_configs:
    - SBLkConfigDefault
    - ESTkConfigDefault
   ...
  projection_evaluator: joints(panda_joint1,panda_joint2)
```
